Repository Jejudo-Ticket/client, pull requests merged in 2025-08, with the labels that each got.

#77 refactor : 마감임박펀딩 연결
  frontend-set/src/components/funding/FundingUrgentCard.vue
  frontend-set/src/pages/HomePage.vue
  frontend-set/src/pages/funding/FundingJoinWithoutPaymentPage.vue
  frontend-set/src/pages/funding/FundingListPage.vue
Labels: refactor

#108 Feat :관심 기반 펀딩 연결
  frontend-set/src/api/fundingApi.js
  frontend-set/src/components/funding/FundingCard.vue
  frontend-set/src/components/funding/FundingUrgentCard.vue
  frontend-set/src/components/home/MainSlideBanner.vue
  frontend-set/src/components/home/RecommendedFundings.vue
  frontend-set/src/components/project/ProjectRankingCard.vue
  frontend-set/src/pages/HomePage.vue
  frontend-set/src/pages/funding/FundingCreateDonationPage.vue
  frontend-set/src/pages/funding/FundingDetailPage.vue
  frontend-set/src/pages/funding/FundingListPage.vue
  frontend-set/src/utils/fundingUtils.js
Labels: feature

#114 refactor: 대시보드 수정
  .DS_Store
  frontend-set/src/pages/mypage/DashBoardPage.vue
Labels: refactor

#118 refactor: 도메인 기재
  .DS_Store
  frontend-set/vite.config.js
Labels: refactor

#126 refactor: 관리자 대출 기능 관련 리팩토링
  .DS_Store
  frontend-set/src/api/userLoanApi.js
  frontend-set/src/components/admin/ApplicantList.vue
  frontend-set/src/pages/admin/LoanManagementPage.vue
Labels: refactor

#130 feat: 챌린지 admin 검증 기능 페이지 구현
  .DS_Store
  frontend-set/src/api/challengeAdminApi.js
  frontend-set/src/pages/admin/ChallengeLogVerificationPage.vue
  frontend-set/src/pages/admin/ChallengeParticipantListPage.vue
  frontend-set/src/router/admin.js
Labels: feature

#131 Refactor : front 최종 수정!🥹
  frontend-set/src/components/common/SuccessPopup.vue
  frontend-set/src/components/project/list/ProjectCard.vue
  frontend-set/src/pages/funding/FundingCreateChallengePage.vue
  frontend-set/src/pages/funding/FundingCreateDonationPage.vue
  frontend-set/src/pages/funding/FundingCreateLoanPage.vue
  frontend-set/src/pages/funding/FundingCreateSavingsPage.vue
  frontend-set/src/pages/funding/FundingDetailPage.vue
  frontend-set/src/pages/funding/FundingJoinPage.vue
  frontend-set/src/pages/funding/FundingJoinWithPaymentPage.vue
  frontend-set/src/pages/funding/FundingJoinWithoutPaymentPage.vue
  frontend-set/src/pages/project/components/DonationProjectInput.vue
  frontend-set/src/pages/project/components/LoanProjectInput.vue
Labels: refactor

#142 feat: 대시보드 챌린지 관리 페이지 구현
  .DS_Store
  frontend-set/src/api/fundApi.js
  frontend-set/src/pages/admin/MyChallengeListPage.vue
  frontend-set/src/pages/mypage/DashBoardPage.vue
  frontend-set/src/router/admin.js
Labels: feature

#146 fix: 첼린지 bug fix + modal 기능 구현
  frontend-set/src/api/challengeAdminApi.js
  frontend-set/src/api/fundApi.js
  frontend-set/src/components/common/AlertModal.vue
  frontend-set/src/pages/admin/ChallengeLogVerificationPage.vue
Labels: bug, feature

#179 feat: 내가 기부한 기부내역 조회
  frontend-set/src/components/mypage/MyDonationsSection.vue
  frontend-set/src/pages/mypage/MyPage.vue
Labels: feature
